schema_version = "1.0.0"


id = "mengges_dark_theme"
version = "1.0.2"
name = "MengGe's Dark Theme"
tagline = "Dark Theme Pro Max Ultra Plus Lift"
maintainer = "MengGe_KKD <menggekkd@gmail.com>"

type = "theme"

tags = ["Dark"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]